import { CurrencyInfo } from './currency.types';

export const DEFAULT_API_KEY =
  process.env.FREECURRENCY_API_KEY || '4E0VK7BnkdeUuh1vegAt808v2IUjzUR6lxcvBMT2';

export const FREECURRENCY_BASE_URL = 'https://api.freecurrencyapi.com/v1';

// Comprehensive metadata for FreeCurrencyAPI supported currencies with flags & symbols
export const SUPPORTED_CURRENCIES: Record<string, CurrencyInfo> = {
  USD: {
    code: 'USD',
    name: 'US Dollar',
    symbol: '$',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'US dollars',
    countries: ['United States', 'Ecuador', 'El Salvador', 'Panama'],
    flag: '🇺🇸',
  },
  EUR: {
    code: 'EUR',
    name: 'Euro',
    symbol: '€',
    symbol_native: '€',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Euros',
    countries: ['Germany', 'France', 'Italy', 'Spain', 'Netherlands', 'European Union'],
    flag: '🇪🇺',
  },
  GBP: {
    code: 'GBP',
    name: 'British Pound Sterling',
    symbol: '£',
    symbol_native: '£',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'British pounds sterling',
    countries: ['United Kingdom', 'Isle of Man', 'Jersey', 'Guernsey'],
    flag: '🇬🇧',
  },
  JPY: {
    code: 'JPY',
    name: 'Japanese Yen',
    symbol: '¥',
    symbol_native: '￥',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Japanese yen',
    countries: ['Japan'],
    flag: '🇯🇵',
  },
  AUD: {
    code: 'AUD',
    name: 'Australian Dollar',
    symbol: 'AU$',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Australian dollars',
    countries: ['Australia', 'Christmas Island', 'Cocos Islands', 'Norfolk Island', 'Tuvalu'],
    flag: '🇦🇺',
  },
  CAD: {
    code: 'CAD',
    name: 'Canadian Dollar',
    symbol: 'CA$',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Canadian dollars',
    countries: ['Canada'],
    flag: '🇨🇦',
  },
  CHF: {
    code: 'CHF',
    name: 'Swiss Franc',
    symbol: 'CHF',
    symbol_native: 'CHF',
    decimal_digits: 2,
    rounding: 0.05,
    name_plural: 'Swiss francs',
    countries: ['Switzerland', 'Liechtenstein'],
    flag: '🇨🇭',
  },
  CNY: {
    code: 'CNY',
    name: 'Chinese Yuan',
    symbol: 'CN¥',
    symbol_native: '¥',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Chinese yuan',
    countries: ['China'],
    flag: '🇨🇳',
  },
  INR: {
    code: 'INR',
    name: 'Indian Rupee',
    symbol: '₹',
    symbol_native: '₹',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Indian rupees',
    countries: ['India', 'Bhutan'],
    flag: '🇮🇳',
  },
  SGD: {
    code: 'SGD',
    name: 'Singapore Dollar',
    symbol: 'S$',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Singapore dollars',
    countries: ['Singapore'],
    flag: '🇸🇬',
  },
  HKD: {
    code: 'HKD',
    name: 'Hong Kong Dollar',
    symbol: 'HK$',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Hong Kong dollars',
    countries: ['Hong Kong'],
    flag: '🇭🇰',
  },
  NZD: {
    code: 'NZD',
    name: 'New Zealand Dollar',
    symbol: 'NZ$',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'New Zealand dollars',
    countries: ['New Zealand', 'Cook Islands', 'Niue', 'Pitcairn Islands', 'Tokelau'],
    flag: '🇳🇿',
  },
  SEK: {
    code: 'SEK',
    name: 'Swedish Krona',
    symbol: 'kr',
    symbol_native: 'kr',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Swedish kronor',
    countries: ['Sweden'],
    flag: '🇸🇪',
  },
  KRW: {
    code: 'KRW',
    name: 'South Korean Won',
    symbol: '₩',
    symbol_native: '₩',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'South Korean won',
    countries: ['South Korea'],
    flag: '🇰🇷',
  },
  BRL: {
    code: 'BRL',
    name: 'Brazilian Real',
    symbol: 'R$',
    symbol_native: 'R$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Brazilian reals',
    countries: ['Brazil'],
    flag: '🇧🇷',
  },
  MXN: {
    code: 'MXN',
    name: 'Mexican Peso',
    symbol: 'MX$',
    symbol_native: '$',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Mexican pesos',
    countries: ['Mexico'],
    flag: '🇲🇽',
  },
  NOK: {
    code: 'NOK',
    name: 'Norwegian Krone',
    symbol: 'kr',
    symbol_native: 'kr',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Norwegian kroner',
    countries: ['Norway', 'Svalbard and Jan Mayen', 'Bouvet Island'],
    flag: '🇳🇴',
  },
  TRY: {
    code: 'TRY',
    name: 'Turkish Lira',
    symbol: 'TL',
    symbol_native: 'TL',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Turkish Lira',
    countries: ['Turkey'],
    flag: '🇹🇷',
  },
  RUB: {
    code: 'RUB',
    name: 'Russian Ruble',
    symbol: 'RUB',
    symbol_native: 'руб.',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Russian rubles',
    countries: ['Russia'],
    flag: '🇷🇺',
  },
  ZAR: {
    code: 'ZAR',
    name: 'South African Rand',
    symbol: 'R',
    symbol_native: 'R',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'South African rand',
    countries: ['South Africa'],
    flag: '🇿🇦',
  },
  PLN: {
    code: 'PLN',
    name: 'Polish Zloty',
    symbol: 'zł',
    symbol_native: 'zł',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Polish zlotys',
    countries: ['Poland'],
    flag: '🇵🇱',
  },
  ILS: {
    code: 'ILS',
    name: 'Israeli New Sheqel',
    symbol: '₪',
    symbol_native: '₪',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Israeli new sheqels',
    countries: ['Israel', 'Palestinian Territories'],
    flag: '🇮🇱',
  },
  DKK: {
    code: 'DKK',
    name: 'Danish Krone',
    symbol: 'Dkr',
    symbol_native: 'kr',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Danish kroner',
    countries: ['Denmark', 'Faroe Islands', 'Greenland'],
    flag: '🇩🇰',
  },
  CZK: {
    code: 'CZK',
    name: 'Czech Republic Koruna',
    symbol: 'Kč',
    symbol_native: 'Kč',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Czech Republic korunas',
    countries: ['Czech Republic'],
    flag: '🇨🇿',
  },
  HUF: {
    code: 'HUF',
    name: 'Hungarian Forint',
    symbol: 'Ft',
    symbol_native: 'Ft',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Hungarian forints',
    countries: ['Hungary'],
    flag: '🇭🇺',
  },
  IDR: {
    code: 'IDR',
    name: 'Indonesian Rupiah',
    symbol: 'Rp',
    symbol_native: 'Rp',
    decimal_digits: 0,
    rounding: 0,
    name_plural: 'Indonesian rupiahs',
    countries: ['Indonesia'],
    flag: '🇮🇩',
  },
  MYR: {
    code: 'MYR',
    name: 'Malaysian Ringgit',
    symbol: 'RM',
    symbol_native: 'RM',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Malaysian ringgits',
    countries: ['Malaysia'],
    flag: '🇲🇾',
  },
  PHP: {
    code: 'PHP',
    name: 'Philippine Peso',
    symbol: '₱',
    symbol_native: '₱',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Philippine pesos',
    countries: ['Philippines'],
    flag: '🇵🇭',
  },
  THB: {
    code: 'THB',
    name: 'Thai Baht',
    symbol: '฿',
    symbol_native: '฿',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Thai baht',
    countries: ['Thailand'],
    flag: '🇹🇭',
  },
  AED: {
    code: 'AED',
    name: 'United Arab Emirates Dirham',
    symbol: 'AED',
    symbol_native: 'د.إ',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'UAE dirhams',
    countries: ['United Arab Emirates'],
    flag: '🇦🇪',
  },
  SAR: {
    code: 'SAR',
    name: 'Saudi Riyal',
    symbol: 'SR',
    symbol_native: 'ر.س',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Saudi riyals',
    countries: ['Saudi Arabia'],
    flag: '🇸🇦',
  },
  PKR: {
    code: 'PKR',
    name: 'Pakistani Rupee',
    symbol: 'PKR',
    symbol_native: '₨',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Pakistani rupees',
    countries: ['Pakistan'],
    flag: '🇵🇰',
  },
  EGP: {
    code: 'EGP',
    name: 'Egyptian Pound',
    symbol: 'EGP',
    symbol_native: 'ج.م',
    decimal_digits: 2,
    rounding: 0,
    name_plural: 'Egyptian pounds',
    countries: ['Egypt'],
    flag: '🇪🇬',
  },
};

// Fallback baseline exchange rates relative to USD (used only if FreeCurrencyAPI quota is exceeded)
export const FALLBACK_USD_RATES: Record<string, number> = {
  USD: 1.0,
  EUR: 0.9235,
  GBP: 0.7891,
  JPY: 154.65,
  AUD: 1.524,
  CAD: 1.368,
  CHF: 0.897,
  CNY: 7.235,
  INR: 83.45,
  SGD: 1.348,
  HKD: 7.821,
  NZD: 1.642,
  SEK: 10.62,
  KRW: 1375.5,
  BRL: 5.185,
  MXN: 16.92,
  NOK: 10.85,
  TRY: 32.45,
  RUB: 91.5,
  ZAR: 18.75,
  PLN: 3.98,
  ILS: 3.72,
  DKK: 6.89,
  CZK: 23.25,
  HUF: 362.4,
  IDR: 16240.0,
  MYR: 4.72,
  PHP: 57.85,
  THB: 36.75,
  AED: 3.6725,
  SAR: 3.75,
  PKR: 278.4,
  EGP: 47.9,
};
